### ISSUE TITLE
WS ERROR with latest weechat

### ISSUE THREAD

**Issue by sQVe** [wee-slack/wee-slack#676]
_Thank you for this awesome plugin!_ :pray:

I'm seeing a very strange issue with `wee-slack` when using the latest `weechat`. I'm getting a **Python** `WS ERROR` as soon as I try to send a message somewhere. I'm using **ArchLinux** and see this issue as soon as I use either `weechat@2.3-2` or `weechat-git`. 

As soon as I downgrade to `weechat@2.3-1` it works as expected. What is even more strange is that the difference, from what I can see, between `weechat@2.3-1` and `weechat@2.3-2` is Ruby rebuild for `2.6`.

I can easily replicate this and I've tried it so far on three machines. Let me know how I can further help to solve this issue! :beers:

**Comment by sQVe** [comment]
This seems somewhat related to https://github.com/wee-slack/wee-slack/issues/656.

**Comment by gianarb** [comment]
I think so and I am on Arch Linux too

**Comment by trygveaa** [comment]
Hm, apparently lots of people are having such issues :/ (#671 also seems relevant). However, I can't reproduce it, so I have no idea why it happens. (I'm also testing on two Arch machines currently using weechat 2.3-2).

I just pushed some changes so the debug messages should be more helpful. Could you enable debug mode (`/set plugins.var.python.slack.debug_mode true`), and report what is printed both in the core/team buffers and the debug buffer?

**Comment by sQVe** [comment]
The **slack** buffer is continuously outputting:

```
Failed connecting to slack team {secret}, retrying.
```

The **slack-debug** buffer is continuously outputting:

```
DEBUG: connect failed with exception:
Traceback (most recent call last):
  File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 1184, in connect
    ws = create_connection(self.ws_url, sslopt=sslopt_ca_certs)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 511, in create_connection
    websock.connect(url, **options)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 186, in _open_socket
    raise error
error: [Errno 4] Interrupted system call
```

When trying to _send a message_ the **weechat** buffer outputs:

```
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr (slack):   File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 741, in buffer_input_callback
python: stdout/stderr (slack):     channel.send_message(data)
python: stdout/stderr (slack):   File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 1618, in send_message
python: stdout/stderr (slack):     self.team.send_to_websocket(request)
python: stdout/stderr (slack):   File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 1236, in send_to_websocket
python: stdout/stderr (slack):     self.set_disconnected()
python: stdout/stderr (slack):   File "/home/sqve/.weechat/python/autoload/wee_slack.py", line 1213, in set_disconnected
python: stdout/stderr (slack):     w.unhook(self.hook)
python: stdout/stderr (slack): AttributeError: 'SlackTeam' object has no attribute 'hook'
=!= python: error in function "buffer_input_callback"
```

Give me a ping if I can provide anything else.

**Comment by trygveaa** [comment]
@sQVe: I saw another person get `[Errno 4] Interrupted system call` too, but I have no idea what could cause that.

I wrote a very simple script which just connects to Slack, to figure out where the problem lies. Could you try that, both in weechat and from the command line, and report any output? Insert the token in the script where the placeholder is.

```
#!/usr/bin/python2
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from websocket import create_connection
import json
import urllib2

try:
    import weechat
except:
    weechat = None

TOKEN='INSERT_TOKEN_HERE'

SCRIPT_NAME = "slack-test"
SCRIPT_AUTHOR = "trygveaa"
SCRIPT_VERSION = "0.1"
SCRIPT_LICENSE = "MIT"
SCRIPT_DESC = "Simple test of Slack connection"

slack_url = 'https://api.slack.com/api/rtm.connect?token=' + TOKEN

def connect_ws(rtm):
    url = json.loads(rtm).get('url')
    if url:
        ws = create_connection(url)
        response = ws.recv()
        ws.close()
        return response
    else:
        return 'missing url, got: ' + rtm

def connect_urllib2():
    rtm = urllib2.urlopen(slack_url).read()
    return connect_ws(rtm)

def connect_weechat():
    weechat.hook_process_hashtable('url:' + slack_url, {}, 60000, 'callback_connect', '')

def callback_connect(data, command, return_code, out, err):
    if return_code == 0 and not err:
        weechat.prnt('', 'connect with weechat: ' + connect_ws(out))
    else:
        weechat.prnt('', 'connect with weechat failed: {} - {} - {}'.format(return_code, out, err))
    return weechat.WEECHAT_RC_OK

if __name__ == "__main__":
    if weechat:
        weechat.register(SCRIPT_NAME, SCRIPT_AUTHOR, SCRIPT_VERSION, SCRIPT_LICENSE, SCRIPT_DESC, '', '')
        weechat.prnt('', 'connect with urllib2: ' + connect_urllib2())
        connect_weechat()
    else:
        print('connect with urllib2: ' + connect_urllib2())
```

**Comment by sQVe** [comment]
@trygveaa 

Running from terminal gives me:

```sh
% ./slack.test.py
connect with urllib2: {"type": "hello"}
```

Running as a weechat python plugin gives me:

```
python: stdout/stderr (slack-test): Traceback (most recent call last):
python: stdout/stderr (slack-test):   File "/home/sqve/.weechat/python/autoload/slacktest.py", line 52, in <module>
python: stdout/stderr (slack-test):     weechat.prnt('', 'connect with urllib2: ' + connect_urllib2())
python: stdout/stderr (slack-test):   File "/home/sqve/.weechat/python/autoload/slacktest.py", line 38, in connect_urllib2
python: stdout/stderr (slack-test):     return connect_ws(rtm)
python: stdout/stderr (slack-test):   File "/home/sqve/.weechat/python/autoload/slacktest.py", line 28, in connect_ws
python: stdout/stderr (slack-test):     ws = create_connection(url)
python: stdout/stderr (slack-test):   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 511, in create_connection
python: stdout/stderr (slack-test):     websock.connect(url, **options)
python: stdout/stderr (slack-test):   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 220, in connect
python: stdout/stderr (slack-test):     options.pop('socket', None))
python: stdout/stderr (slack-test):   File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 120, in connect
python: stdout/stderr (slack-test):     sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
python: stdout/stderr (slack-test):   File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 186, in _open_socket
python: stdout/stderr (slack-test):     raise error
python: stdout/stderr (slack-test): socket.error: [Errno 4] Interrupted system call
```

**Comment by alexeicolin** [comment]
To save others time from trying: "Interrupted system call" still happens on Weechat 2.4 released today. With wee-slack 2.2.0 the error is "WS Error".

**Comment by trygveaa** [comment]
I have looked into this issue, and as far as I can see this is something which has to be handled in the websocket library. For more details see https://github.com/weechat/weechat/issues/1305 and https://github.com/websocket-client/websocket-client/issues/527.

I have submitted a PR against websocket-client with a fix for the issue: https://github.com/websocket-client/websocket-client/pull/528

I don't think there's anything we can do about this in wee-slack, so we'll have to wait for that PR to be merged. In the mean time, feel free to test the PR to confirm it fixes the issue.

**Comment by alexeicolin** [comment]
Confirming that websocket-client/websocket-client#528 fixes the issue for me in Weechat 2.4

**Comment by puresick** [comment]
> Confirming that [websocket-client/websocket-client#528](https://github.com/websocket-client/websocket-client/pull/528) fixes the issue for me in Weechat 2.4.
> Arch users if you want to get this fix quickly, here's a patch to the PKGBUILD to merge the PR:
> 
> ```
> git clone https://aur.archlinux.org/python-websocket-client-git.git
> git clone https://gist.github.com/alexeicolin/3f3a9cdc62ac6078fd22b7368b064e21
> cd python-websocket-client-git
> git am ../3f3a9cdc62ac6078fd22b7368b064e21/*
> makepkg -si
> ```

sadly this did not resolved the `WS ERROR` issues on Arch Linux with `weechat-git-2.4.16.g33581dd1a-1` on my machine.

**Comment by trygveaa** [comment]
I see that Arch has actually applied my patch to the package. So if you're using Arch, and websocket-client installed with pacman, you can just update.

**Comment by gianarb** [comment]
```
community/python-websocket-client 0.55.0-1 [installed]
    WebSocket client library for Python
```
This is the version of websocket I have installed but I still get the issue `AttributeError: 'SlackTeam' object has no attribute 'hook'`. Let me know how I can help! I would like to get back to weechat!! :dancer:

**Comment by trygveaa** [comment]
@gianarb: websocket-client 0.55 is unfortunately broken, because of another change that was included in that release. See https://github.com/wee-slack/wee-slack/issues/679#issuecomment-472383899 for more details. I'm working on a fix.

**Comment by gianarb** [comment]
Ah thanks a lot for your hard work, should I try to use 0.54 or what? Do you have a good version that I should try? :) Thanks

**Comment by trygveaa** [comment]
0.54 is more likely to work than 0.55, but if you experience the same issue as others in this thread, none of the versions will work. If so, you will have to patch websocket-client yourself, e.g. by using the patch in https://github.com/wee-slack/wee-slack/issues/679#issuecomment-472383899 (that patch is for 0.55).

**Comment by trygveaa** [comment]
This has been fixed in websocket-client version 0.56.0 (technically, this issue was fixed in 0.55.0, but as mentioned above, 0.55.0 is broken).

**Comment by scottro11** [comment]
I know this is closed, but I just ran into the same issue on FreeBSD-11.2-RELEASE after upgrading to weechat 2.5.  py27-websocket-client is at version py27-websocket-client-0.56.0_1
So I don't know if websocket was the issue, it seems to be with weechat.
As has been said, thank you by the way, for this awesome plugin.

**Comment by scottro11** [comment]
Apologies, forgot to mention that it works as expected if  I downgrading weechat to 2.3 (which was the version in /var/cache/pkg.

**Comment by trygveaa** [comment]
@scottro11: [Enable debug mode] (https://github.com/wee-slack/wee-slack#development) and post what's printed in the core and debug buffers.

**Comment by scottro11** [comment]
I will do on a separate install, (I need my workstation's install. I may not do this till the weekend, please give me some time, and thank you for your help.

**Comment by scottro11** [comment]
I installed a VM and tried the debugging, but I'm not sure what I missed (I have little knowledge of either python or weechat). I didn't get any output in core or debug buffers.  Same with Fedora and Arch, I am missing something so not getting output. In Arch, at least, a solution from last year made it work for me. 

https://github.com/wee-slack/wee-slack/issues/122

**Comment by trygveaa** [comment]
@scottro11: I'm not sure what's going on for you. Please describe exactly what you are doing and what's happening in weechat. Are you sure you're not getting any output at all? Which buffers are created when you load the script?

Why did you post in that other issue? Does your error have any relation to cafile/capath/cadata which that issue is about? What is the solution you're referring to which worked for you? If you're referring to the last comment in that issue, that only describes installing the required dependency.

**Comment by scottro11** [comment]
Apologies for lack of clarity and may not be able to give you a more detailed answer for a few days. 
To give you a quick answer from memory. 
While trying to follow debug mode, I did not know how to do this part.

To run the tests, create a virtualenv and pip install from the requirements.txt. Then pytest to run them locally.


I did this part, and got responses that the changes had been made.
/set plugins.var.python.slack.debug_mode on
/set plugins.var.python.slack.debug_level 2

I did this part, but there was no /tmp/weeslack-debug directory or file
Dump the JSON responses in /tmp/weeslack-debug/. Requires a script reload.
/set plugins.var.python.slack.record_events true

I mentioned the ArchLinux fix because generally (and admittedly vaguely) the issue seems to be that with later versions of weechat it's having issues reading the wee_slack.py. When I made the changes suggested in ArchLinux, it was able to read the script. 

Fedora, Arch, and FreeBSD, in various tests, are not loading the script (As I said, I'll follow with more detailed info in a few days).  With FreeBSD, I can get it working by downgrading to weechat-4.3.  With Arch, I got it working by followiing those instructions from https://github.com/wee-slack/wee-slack/issues/122

This has been consistent with quick tests with Arch, Fedora and FreeBSD.  All used to work without issue simply following the instructions on the main page, but since various weechat upgrades (and probably connected with python upgrades as well, I've only gotten FreeBSD to work by using an older weechat version, and Arch to work by following those instructions in bug 122. 

Again, I'll give more detailed output in a few days, and thanks for trying to help despite my lack of knowledge.

**Comment by scottro11** [comment]
Ok, on a fresh FreeBSD-11.2-RELEASE in VirtualBox, when I start weechat I get


 buflist: warning: the script buffers.pl is loaded and provides a bar with list of buffers similar to the buflist plugin; you may want to
         ≠             | uninstall the script buffers.pl (/script remove buffers.pl) or disable/unload the buflist plugin; see WeeChat release notes for more
         ≠             | information
         ≠06:30:51     | perl scripts loaded: buffers
         ≠06:30:51 =!= | Bind error: [Errno 8] hostname nor servname provided, or not known
         ≠06:30:51     | URL server not running
         ≠06:30:51     | python: stdout/stderr (?):   File "/usr/home/scottro/.weechat/python/autoload/wee_slack.py", line 1236
         ≠06:30:51     | python: stdout/stderr (?):     print "WS ERROR"
         ≠06:30:51     | python: stdout/stderr (?):                    ^
         ≠06:30:51     | python: stdout/stderr (?): SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WS ERROR")?
         ≠06:30:51 =!= | python: unable to parse file "/usr/home/scottro/.weechat/python/autoload/wee_slack.py"
         ≠06:30:51     | python scripts loaded: autojoin, urlserver
         ≠06:30:51     | script: 359 scripts for WeeChat 2.5
         ≠06:30:51     | Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, lua, perl, python, relay, ruby, script, spell, tcl, trigger, xfer
         ≠
I then run the set plugins./var.python.slack.debug_mode on and get a message the option has been changed to on
I set debug to level 2 and get a message this has been done
I set record events to true and get a message that this has been done

I try to connect to slack with /connect slack.  The only buffer that is open is the main weechat one, buffer 1.  
The message I am getting is irc reconnecting to server in 10 seconds

This is with weechat-2.5.  With weechat-2.3 it works as expected.

**Comment by trygveaa** [comment]
@scottro11: You're running an old version of wee-slack. Upgrade to the latest.

**Comment by scottro11** [comment]
At present I have

py27-six-1.12.0                Python 2 and 3 compatibility utilities
py27-websocket-client-0.56.0_1 Websocket client for python

When I get the latest weechat_py, I now get an error

 python: stdout/stderr (?): Traceback (most recent call last):
         ≠06:56:06     | python: stdout/stderr (?):   File "/usr/home/scottro/.weechat/python/autoload/wee_slack.py", line 33, in <module>
         ≠06:56:06     | python: stdout/stderr (?):     from websocket import ABNF, create_connection, WebSocketConnectionClosedException
         ≠06:56:06     | python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
         ≠06:56:06 =!= | python: unable to parse file "/usr/home/scottro/.weechat/python/autoload/wee_slack.py"
         ≠06:56:06     | python scripts loaded: autojoin, urlserver
         ≠06:56:06     | script: 359 scripts for WeeChat 2.5
         ≠06:56:06     | Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, lua, perl, python, relay, ruby, script, spell, tcl, trigger, xfer
         ≠
The instructions need to be updated. I fixed it by installing py36-websocket-client which pulled in py36-six. It now runs.
Thank you for your patience and help here. I think that the instructions for FreeBSD should be updated (and maybe for Linux as well?)
Thanks again.

**Comment by scottro11** [comment]
I see the FreeBSD instructions now say py36-websocket-client. Was that up there and I was looking at a cached page or did you just do it? Regardless, thanks again.

**Comment by trygveaa** [comment]
Yeah, I updated it just now.
